
# PowerShell 5.0 build worker
os: WMF 5

# Secret deployment keys
environment:
  PSGalleryKey:
    secure: +o4/iom8ZO0TkCMSM0gInMHq/ioFlK7LRh2jJULTBejba3nCjp2EOv94DcTS2r20
  GitHubToken:
    secure: g7atusVu/SvLWa4397EhDExCquI2srCWwO2JetLpnQ57V8Pzm27Eq9kj/v8X6wkd

# Install required Pester and PSScriptAnalyzer modules
install:
  - ps: Install-PackageProvider NuGet -Force | Out-Null
  - ps: Install-Module psake -Force
  - ps: Install-Module Pester -Force
  - ps: Install-Module PSScriptAnalyzer -Force

# Set version to build number
version: '{build}'

# Build configuration
configuration: Release
platform: Any CPU

# Execute psake build task
build_script:
  - ps: >-
      Invoke-psake build.psake.ps1 -taskList Build -notr

# Execute psake test and analyze task
test_script:
  - ps: >-
      Invoke-psake build.psake.ps1 -taskList Pester, ScriptAnalyzer -notr

# Execute psake deploy task
deploy_script:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq 'true')
      {
        Invoke-psake build.psake.ps1 -taskList Gallery, GitHub -properties @{ GalleryKey = $Env:PSGalleryKey; GitHubKey = $Env:GitHubToken } -notr
      }
