
# PowerShell 5.0 build worker
os: WMF 5

# Install required Pester and PSScriptAnalyzer modules
install:
  - ps: Install-PackageProvider NuGet -Force | Out-Null
  - ps: Install-Module posh-git -Force
  - ps: Install-Module SecurityFever -Force
  - ps: Install-Module psake -Force
  - ps: Install-Module Pester -Force
  - ps: Install-Module PSScriptAnalyzer -Force

# Set version to build number
version: '{build}'

# Build configuration
configuration: Release
platform: Any CPU

# Execute psake build task
build_script:
  - ps: >-
      Invoke-psake build.psake.ps1 -taskList Build -notr

# Execute psake test and analyze task
test_script:
  - ps: >-
      Invoke-psake build.psake.ps1 -taskList Pester, ScriptAnalyzer -notr
